[package]
name = "swupdate-httpd"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = "1.0.219"
serde_derive = "1.0.219"
clap = { version = "4.5.13", features = ["derive"] }
